# Generated by Django 5.2 manually

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS delivery_records (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tracking_number VARCHAR(100) NOT NULL,
                status VARCHAR(20) NOT NULL,
                assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                picked_up_at TIMESTAMP NULL,
                delivered_at TIMESTAMP NULL,
                delivery_notes TEXT DEFAULT '',
                delivery_cost DECIMAL(10, 2) NOT NULL DEFAULT 0.0,
                order_id INTEGER NOT NULL UNIQUE REFERENCES orders_order(id) ON DELETE CASCADE,
                driver_id INTEGER NULL REFERENCES users_user(id) ON DELETE SET NULL
            );
            """,
            """
            DROP TABLE IF EXISTS delivery_records;
            """
        ),
    ] 