# Generated by Django 5.2.1 on 2025-05-27 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_create_delivery_records_table'),
        ('orders', '0005_alter_order_status'),
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ['name'], 'verbose_name': 'Delivery Company', 'verbose_name_plural': 'Delivery Companies'},
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='base_cost',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='deliveryrecord',
            name='delivery_company',
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Assigned At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Delivery Cost'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Delivery Notes'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Picked Up At'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='assigned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryrecord',
            name='tracking_number',
            field=models.CharField(max_length=100, verbose_name='Tracking Number'),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('current_location', models.CharField(blank=True, max_length=255, verbose_name='Current Location')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='delivery.deliverycompany', verbose_name='Company')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='couriers', to='settings.country', verbose_name='Service Areas')),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'db_table': 'couriers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecordEnhanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='Tracking Number')),
                ('barcode', models.TextField(blank=True, verbose_name='Barcode')),
                ('status', models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending_assignment', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='Pickup Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Delivery Notes')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Cost')),
                ('delivery_proof', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='Delivery Proof')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='customer_signatures/', verbose_name='Customer Signature')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='Failure Reason')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry Count')),
                ('next_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Next Attempt')),
                ('call_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Call Agent')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier', verbose_name='Courier')),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycompany', verbose_name='Delivery Company')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_enhanced', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Enhanced Delivery Record',
                'verbose_name_plural': 'Enhanced Delivery Records',
                'db_table': 'delivery_records_enhanced',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status_history', to='orders.order', verbose_name='Order')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Delivery Status History',
                'verbose_name_plural': 'Delivery Status History',
                'db_table': 'delivery_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
