# Generated by Django 5.2 on 2025-06-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliverycompany_options_and_more'),
        ('orders', '0006_order_customer_email_order_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vehicle Type'),
        ),
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Accuracy')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Battery Level')),
                ('connection_type', models.CharField(choices=[('wifi', 'WiFi'), ('cellular', 'Cellular'), ('offline', 'Offline')], default='cellular', max_length=20, verbose_name='Connection Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='delivery.courier', verbose_name='Courier')),
            ],
            options={
                'verbose_name': 'Courier Location',
                'verbose_name_plural': 'Courier Locations',
                'db_table': 'courier_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('status', models.CharField(choices=[('active', 'Active'), ('break', 'Break'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('device_info', models.TextField(blank=True, verbose_name='Device Info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='delivery.courier', verbose_name='Courier')),
            ],
            options={
                'verbose_name': 'Courier Session',
                'verbose_name_plural': 'Courier Sessions',
                'db_table': 'courier_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Attempt Number')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Attempt Time')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('rescheduled', 'Rescheduled')], default='failed', max_length=20, verbose_name='Status')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Failure Reason')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='Customer Feedback')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_attempts/', verbose_name='Proof Image')),
                ('signature_data', models.TextField(blank=True, verbose_name='Signature Data')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('next_attempt_date', models.DateTimeField(blank=True, null=True, verbose_name='Next Attempt Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='delivery.courier', verbose_name='Courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'db_table': 'delivery_attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('photo', 'Photo'), ('signature', 'Signature'), ('barcode', 'Barcode'), ('otp', 'OTP')], default='photo', max_length=20, verbose_name='Proof Type')),
                ('proof_data', models.TextField(blank=True, verbose_name='Proof Data')),
                ('capture_time', models.DateTimeField(auto_now_add=True, verbose_name='Capture Time')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='delivery.courier', verbose_name='Courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Delivery Proof',
                'verbose_name_plural': 'Delivery Proofs',
                'db_table': 'delivery_proofs',
                'ordering': ['-capture_time'],
            },
        ),
    ]
