# Generated by Django 5.2 on 2025-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounting_department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='accounting department'),
        ),
        migrations.AddField(
            model_name='user',
            name='call_center_team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='call center team'),
        ),
    ]
