# Generated by Django 5.2 on 2025-06-19 19:04

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),  # Make sure roles migration runs first
        ('users', '0002_user_accounting_department_user_call_center_team'),
    ]

    operations = [
        # First, create a superadmin role
        migrations.RunSQL(
            """
            INSERT INTO roles_role (name, slug, description, is_system_role, created_at, updated_at, required_fields) 
            VALUES ('Super Admin', 'super_admin', 'Full system access', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '{}')
            """,
            reverse_sql="DELETE FROM roles_role WHERE slug = 'super_admin';"
        ),
        
        # Then update users with role='super_admin' to use the new role ID
        migrations.RunSQL(
            """
            UPDATE users_user 
            SET role_id = (SELECT id FROM roles_role WHERE slug = 'super_admin') 
            WHERE role = 'super_admin';
            """,
            reverse_sql="SELECT 1;"
        ),
        
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='granted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.permission'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounting_department',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='accounting department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='call_center_team',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='call center team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role', verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='permission name'),
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission')},
        ),
    ]
