# Generated by Django 5.2 on 2025-06-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0003_alter_auditlog_options_alter_user_options_and_more'),
    ]

    operations = [
        # First, create a superadmin role
        migrations.RunSQL(
            """
            INSERT OR IGNORE INTO roles_role (name, slug, description, is_system_role, created_at, updated_at, required_fields) 
            VALUES ('Super Admin', 'super_admin', 'Full system access', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '{}');
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Then add a role_id column to users_user table
        migrations.RunSQL(
            """
            ALTER TABLE users_user ADD COLUMN role_id INTEGER REFERENCES roles_role(id);
            """,
            reverse_sql="SELECT 1;"
        ),
        
        # Update users with role='super_admin' to use the new role ID
        migrations.RunSQL(
            """
            UPDATE users_user 
            SET role_id = (SELECT id FROM roles_role WHERE slug = 'super_admin')
            WHERE role = 'super_admin';
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
