# Generated by Django 5.2 on 2025-06-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_user_role'),
    ]

    operations = [
        # Add role_id column to users_user table if it doesn't exist
        migrations.RunSQL(
            """
            -- Check if role_id column exists, if not, add it
            PRAGMA foreign_keys=off;
            
            -- Create a temporary table with the desired structure
            CREATE TABLE IF NOT EXISTS users_user_temp (
                id INTEGER PRIMARY KEY,
                password VARCHAR(128) NOT NULL,
                last_login DATETIME NULL,
                is_superuser BOOL NOT NULL,
                first_name VARCHAR(150) NOT NULL,
                last_name VARCHAR(150) NOT NULL,
                is_staff BOOL NOT NULL,
                email VARCHAR(254) NOT NULL UNIQUE,
                full_name VARCHAR(150) NOT NULL,
                phone_number VARCHAR(20) NOT NULL,
                profile_image VARCHAR(100) NULL,
                company_name VARCHAR(100) NOT NULL,
                country VARCHAR(100) NOT NULL,
                expected_daily_orders INTEGER UNSIGNED NOT NULL,
                date_joined DATETIME NOT NULL,
                is_active BOOL NOT NULL,
                call_center_team VARCHAR(50) NULL,
                accounting_department VARCHAR(50) NULL,
                role_id INTEGER NULL REFERENCES roles_role(id)
            );
            
            -- Copy data from the original table to the temporary table
            INSERT OR IGNORE INTO users_user_temp 
            SELECT id, password, last_login, is_superuser, first_name, last_name, is_staff, 
                   email, full_name, phone_number, profile_image, company_name, country, 
                   expected_daily_orders, date_joined, is_active, call_center_team, 
                   accounting_department, NULL as role_id
            FROM users_user;
            
            -- Drop the original table
            DROP TABLE IF EXISTS users_user;
            
            -- Rename the temporary table to the original table name
            ALTER TABLE users_user_temp RENAME TO users_user;
            
            -- Create any necessary indexes
            CREATE INDEX IF NOT EXISTS users_user_role_id_idx ON users_user(role_id);
            
            PRAGMA foreign_keys=on;
            """,
            reverse_sql="SELECT 1;"
        ),
    ] 