# Generated by Django 5.2 on 2025-06-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_role_id_column'),
    ]

    operations = [
        # Add role_id column directly with a simple ALTER TABLE statement
        migrations.RunSQL(
            """
            -- Try to add the role_id column
            ALTER TABLE users_user ADD COLUMN role_id INTEGER REFERENCES roles_role(id);
            """,
            reverse_sql="SELECT 1;"
        ),
    ] 