# Generated by Django 5.2 on 2025-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_role_id_column'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Create the role_id column directly in the database
            -- This is a direct approach that should work even if previous migrations failed
            
            -- First check if the column exists
            PRAGMA table_info(users_user);
            
            -- Add the column if it doesn't exist
            -- SQLite doesn't support IF NOT EXISTS for ALTER TABLE ADD COLUMN
            -- so we'll just try to add it and ignore errors if it already exists
            
            -- Try to add the role_id column
            ALTER TABLE users_user ADD COLUMN role_id INTEGER;
            
            -- Create an index on the role_id column
            CREATE INDEX IF NOT EXISTS users_user_role_id_idx ON users_user(role_id);
            """,
            reverse_sql="SELECT 1;"
        ),
    ] 