# Generated by Django 5.2 on 2025-06-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fix_role_column'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Drop any NOT NULL constraint on the role_id column
            PRAGMA foreign_keys=off;
            
            -- Create a temporary table with the same structure but without the NOT NULL constraint
            CREATE TABLE users_user_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                password VARCHAR(128) NOT NULL,
                last_login DATETIME NULL,
                is_superuser BOOL NOT NULL,
                first_name VARCHAR(150) NOT NULL,
                last_name VARCHAR(150) NOT NULL,
                is_staff BOOL NOT NULL,
                email VARCHAR(254) NOT NULL UNIQUE,
                full_name VARCHAR(150) NOT NULL,
                phone_number VARCHAR(20) NOT NULL,
                profile_image VARCHAR(100) NULL,
                company_name VARCHAR(100) NOT NULL,
                country VARCHAR(100) NOT NULL,
                expected_daily_orders INTEGER UNSIGNED NOT NULL,
                call_center_team VARCHAR(50) NULL,
                accounting_department VARCHAR(50) NULL,
                date_joined DATETIME NOT NULL,
                is_active BOOL NOT NULL,
                role_id INTEGER NULL REFERENCES roles_role (id)
            );
            
            -- Copy data from the old table to the new one
            INSERT INTO users_user_new 
            SELECT id, password, last_login, is_superuser, first_name, last_name, is_staff, 
                   email, full_name, phone_number, profile_image, company_name, country, 
                   expected_daily_orders, call_center_team, accounting_department, 
                   date_joined, is_active, role_id 
            FROM users_user;
            
            -- Drop the old table
            DROP TABLE users_user;
            
            -- Rename the new table to the original name
            ALTER TABLE users_user_new RENAME TO users_user;
            
            -- Recreate indexes
            CREATE INDEX IF NOT EXISTS users_user_role_id_idx ON users_user(role_id);
            
            PRAGMA foreign_keys=on;
            """,
            reverse_sql="SELECT 1;"
        ),
    ] 