# Generated by Django 5.2.1 on 2025-05-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_alter_order_options_remove_order_cancelled_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsell_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Upsell Fees')),
                ('confirmation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Confirmation Fees')),
                ('cancellation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cancellation Fees')),
                ('fulfillment_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fulfillment Fees')),
                ('shipping_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Fees')),
                ('return_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Return Fees')),
                ('warehouse_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Warehouse Fees')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Fees',
                'verbose_name_plural': 'Order Fees',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('postponed', 'Postponed'), ('pending', 'Pending Payment')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
