# Generated by Django 5.2 on 2025-05-27 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Order Payment', 'verbose_name_plural': 'Order Payments'},
        ),
        migrations.RunSQL(
            # Forward SQL - Create or replace finance_payment and finance_orderfees tables
            """
            -- Create finance_payment table
            CREATE TABLE IF NOT EXISTS finance_payment (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL REFERENCES orders_order(id) ON DELETE CASCADE,
                payment_method VARCHAR(20) NOT NULL,
                payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
                payment_date DATETIME NOT NULL,
                created_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL,
                amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
                transaction_id VARCHAR(100) DEFAULT '',
                notes TEXT DEFAULT ''
            );
            
            -- Create finance_orderfees table
            CREATE TABLE IF NOT EXISTS finance_orderfees (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL UNIQUE REFERENCES orders_order(id) ON DELETE CASCADE,
                upsell_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                confirmation_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                cancellation_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                fulfillment_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                shipping_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                return_fees DECIMAL(10, 2) NOT NULL DEFAULT 0,
                warehouse_fees DECIMAL(10, 2) NOT NULL DEFAULT 0
            );
            """,
            # Reverse SQL - No-op
            "SELECT 1;"
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Payment Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterModelTable(
            name='orderfees',
            table='finance_orderfees',
        ),
        migrations.AlterModelTable(
            name='orderpayment',
            table='finance_payment',
        ),
    ]
