# Generated by Django 5.2.1 on 2025-05-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_orderpayment_options_and_more'),
    ]

    operations = [
        # These operations are no longer needed since we're creating the tables with direct SQL
        # and we've already included these fields in the tables we create
    ]
