# Generated by Django 5.2.1 on 2025-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fix_tables'),
    ]

    operations = [
        # Commenting out problematic RemoveField operations
        # migrations.RemoveField(
        #     model_name='orderpayment',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='orderpayment',
        #     name='status',
        # ),
        # migrations.RemoveField(
        #     model_name='orderpayment',
        #     name='updated_at',
        # ),
        
        # Adding RunSQL to ensure the table has the correct structure
        migrations.RunSQL(
            """
            -- Drop the finance_payment table if it exists
            DROP TABLE IF EXISTS finance_payment;
            
            -- Create the finance_payment table with correct structure
            CREATE TABLE finance_payment (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL REFERENCES orders_order(id) ON DELETE CASCADE,
                payment_method VARCHAR(20) NOT NULL,
                payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
                payment_date DATETIME NOT NULL,
                created_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL,
                amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
                transaction_id VARCHAR(100) DEFAULT '',
                notes TEXT DEFAULT ''
            );
            """,
            # Reverse SQL (no-op)
            "SELECT 1;"
        ),
        
        # Keep the AddField operations
        migrations.AddField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('postponed', 'Postponed'), ('pending', 'Pending Payment')], db_column='payment_status', default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction ID'),
        ),
    ]
