# Generated by Django 5.2 on 2025-06-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_orderpayment_created_at_and_more'),
    ]

    operations = [
        # Using RunSQL instead of RemoveField since the fields might not exist
        migrations.RunSQL(
            """
            -- Check if columns exist before trying to remove them
            PRAGMA table_info(finance_payment);
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
