# Generated by Django 5.2 on 2025-06-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_orderpayment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='updated_at',
        ),
    ]
