# Generated by Django 5.2 on 2025-06-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_orderpayment_created_at_and_more'),
    ]

    operations = [
        # Mark the previous migration as applied
        migrations.RunSQL(
            "UPDATE django_migrations SET applied = 1 WHERE app = 'finance' AND name = '0007_remove_orderpayment_created_at_and_more';",
            reverse_sql="SELECT 1;"
        ),
        
        # Ensure the finance_payment table has the correct structure
        migrations.RunSQL(
            """
            -- Create a new table with the correct structure if it doesn't exist
            CREATE TABLE IF NOT EXISTS finance_payment_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                order_id INTEGER NOT NULL REFERENCES orders_order(id) ON DELETE CASCADE,
                payment_method VARCHAR(20) NOT NULL,
                payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
                payment_date DATETIME NOT NULL,
                created_by_id INTEGER REFERENCES auth_user(id) ON DELETE SET NULL,
                amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
                transaction_id VARCHAR(100) DEFAULT '',
                notes TEXT DEFAULT ''
            );
            
            -- Copy data from the old table if it exists
            INSERT OR IGNORE INTO finance_payment_new (id, order_id, payment_method, payment_status, payment_date, created_by_id, amount, transaction_id, notes)
            SELECT id, order_id, payment_method, payment_status, payment_date, created_by_id, amount, transaction_id, notes
            FROM finance_payment;
            
            -- Drop the old table
            DROP TABLE IF EXISTS finance_payment;
            
            -- Rename the new table to the original name
            ALTER TABLE finance_payment_new RENAME TO finance_payment;
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
