# Generated by Django 5.2.1 on 2025-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Available Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Quantity'),
        ),
    ]
