# Generated by Django 5.2.1 on 2025-05-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_product_available_quantity_product_total_quantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='sellers_product',
        ),
    ]
