# Generated by Django 5.2.1 on 2025-05-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='saleschannel',
            table='sellers_saleschannel',
        ),
    ]
