# Generated by Django 5.2.1 on 2025-05-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_saleschannel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='sellers_seller',
        ),
    ]
