# Generated by Django 5.2.1 on 2025-06-04 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_alter_seller_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleschannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sales Channel', 'verbose_name_plural': 'Sales Channels'},
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='country',
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='channel_type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('magento', 'Magento'), ('amazon', 'Amazon'), ('ebay', 'eBay'), ('etsy', 'Etsy'), ('other', 'Other')], default='other', max_length=20, verbose_name='Platform Type'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='last_inventory_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Inventory Sync'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='last_order_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Order Sync'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='last_product_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Product Sync'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='last_shipping_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Shipping Sync'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sales_channels/', verbose_name='Store Logo'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='order_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Order Count'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='pending_sync',
            field=models.PositiveIntegerField(default=0, verbose_name='Pending Sync Items'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='product_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Count'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_inventory',
            field=models.BooleanField(default=True, verbose_name='Sync Inventory'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_orders',
            field=models.BooleanField(default=True, verbose_name='Sync Orders'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_products',
            field=models.BooleanField(default=True, verbose_name='Sync Products'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='sync_shipping',
            field=models.BooleanField(default=True, verbose_name='Sync Shipping Updates'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Revenue'),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Store Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Store Name (English)'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='url',
            field=models.URLField(verbose_name='Store URL'),
        ),
    ]
