# Generated by Django 5.2.1 on 2025-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_alter_saleschannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name='Low Stock Threshold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
