# Generated by Django 5.2.1 on 2025-05-31 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_en'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='deliveryarea',
            options={'ordering': ['country__name_en', 'name_en'], 'verbose_name': 'Delivery Area', 'verbose_name_plural': 'Delivery Areas'},
        ),
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ['name_en'], 'verbose_name': 'Delivery Company', 'verbose_name_plural': 'Delivery Companies'},
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['key'], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='New Value'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Old Value'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(max_length=100, verbose_name='Record ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='table',
            field=models.CharField(max_length=100, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezone',
            field=models.CharField(max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Additional Cost'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Area Code'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='settings.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='countries',
            field=models.ManyToManyField(related_name='delivery_companies', to='settings.country', verbose_name='Operating Countries'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Setting Key'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.CreateModel(
            name='SystemFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upsell_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Upsell Fees')),
                ('confirmation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Confirmation Fees')),
                ('cancellation_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cancellation Fees')),
                ('fulfillment_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fulfillment Fees')),
                ('shipping_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipping Fees')),
                ('return_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Return Fees')),
                ('warehouse_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Warehouse Fees')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'System Fees',
                'verbose_name_plural': 'System Fees',
            },
        ),
    ]
