# Generated by Django 4.2 on 2025-06-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_auditlog_options_alter_country_options_and_more'),
        ('settings', '0003_remove_arabic_fields'),
    ]

    operations = [
    ]
