# Generated by Django 4.2 on 2025-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_merge_20250625_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='deliveryarea',
            options={'ordering': ['country__name', 'name'], 'verbose_name': 'Delivery Area', 'verbose_name_plural': 'Delivery Areas'},
        ),
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ['name'], 'verbose_name': 'Delivery Company', 'verbose_name_plural': 'Delivery Companies'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='deliveryarea',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='deliveryarea',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='deliverycompany',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
