# Generated by Django 5.2.1 on 2025-05-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sourcingrequest',
            table='sourcing_sourcingrequest',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='sourcing_supplier',
        ),
    ]
