# Generated by Django 5.2 on 2025-06-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('users', 'Users'), ('sellers', 'Sellers'), ('inventory', 'Inventory'), ('orders', 'Orders'), ('callcenter', 'Call Center'), ('packaging', 'Packaging'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('warehouse', 'Warehouse'), ('settings', 'Settings'), ('notifications', 'Notifications')], max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted', verbose_name='System Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('required_fields', models.JSONField(blank=True, default=dict, verbose_name='Required Fields')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='roles.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
    ]
