# Generated by Django 5.2.1 on 2025-05-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriber',
            table='subscribers_subscriber',
        ),
    ]
